version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"            
      - "4510-4559:4510-4559"  
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
